PATCH /api/2.3/tenders/16a6ec1ed36341f3b3a6e63ef3dab7b8/qualifications/87a93ba395fe4efb96301f0615a2727a?acc_token=70c750e1bef74c30b496d1d9bc8160df HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "qualified": true, 
    "bidID": "683e61642fdb4c67b0860abad5bbf12f", 
    "date": "2016-12-28T14:52:22.888642+02:00", 
    "id": "87a93ba395fe4efb96301f0615a2727a"
  }
}

