GET /api/2.3/tenders/16a6ec1ed36341f3b3a6e63ef3dab7b8/bids/026b4cc6aef2495a9da7551a78cb3cf7?acc_token=99a0b30453754326836fb1b8dd0c5ff5 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/16a6ec1ed36341f3b3a6e63ef3dab7b8/bids/026b4cc6aef2495a9da7551a78cb3cf7/documents/b129be0aafd843cd8260404e69bc2643?download=4bd4e3e917fc4a6ba6838890a0ec0d6f", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-12-28T14:52:20.730618+02:00", 
        "id": "b129be0aafd843cd8260404e69bc2643", 
        "dateModified": "2016-12-28T14:52:20.730639+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "format": "application/pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/16a6ec1ed36341f3b3a6e63ef3dab7b8/bids/026b4cc6aef2495a9da7551a78cb3cf7/documents/c7ffef4f5d4b4c309c0a072ab549546f?download=6c846ff82fac44d1856042ae7f9b6e25", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_top_secrets.pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-12-28T14:52:20.842132+02:00", 
        "id": "c7ffef4f5d4b4c309c0a072ab549546f", 
        "dateModified": "2016-12-28T14:52:20.842260+02:00"
      }
    ], 
    "selfEligible": true, 
    "id": "026b4cc6aef2495a9da7551a78cb3cf7", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "selfQualified": true, 
    "financialDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/16a6ec1ed36341f3b3a6e63ef3dab7b8/bids/026b4cc6aef2495a9da7551a78cb3cf7/financial_documents/c4e55b3d653e44ddbbf9273ff5bd07c0?download=de28cbbdf7ba44a9bcf163b3306a4736", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-12-28T14:52:21.101689+02:00", 
        "id": "c4e55b3d653e44ddbbf9273ff5bd07c0", 
        "dateModified": "2016-12-28T14:52:21.101710+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/16a6ec1ed36341f3b3a6e63ef3dab7b8/bids/026b4cc6aef2495a9da7551a78cb3cf7/financial_documents/14beea76f5bb4f5c92a1787cdbf36e0b?download=a54d5168322d49239509cdb6fb506a31", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-12-28T14:52:21.225626+02:00", 
        "id": "14beea76f5bb4f5c92a1787cdbf36e0b", 
        "dateModified": "2016-12-28T14:52:21.225648+02:00"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2016-12-28T14:52:20.509201+02:00", 
    "subcontractingDetails": "ДКП «Орфей», Україна", 
    "qualificationDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "qualification_document.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/16a6ec1ed36341f3b3a6e63ef3dab7b8/bids/026b4cc6aef2495a9da7551a78cb3cf7/qualification_documents/5973da0bd1b54035a2412fd6c7e93681?download=290eac1ecfdb459cb84553d4eb2a631f", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-12-28T14:52:21.377061+02:00", 
        "id": "5973da0bd1b54035a2412fd6c7e93681", 
        "dateModified": "2016-12-28T14:52:21.377084+02:00"
      }
    ]
  }
}

