GET /api/2.3/tenders/16a6ec1ed36341f3b3a6e63ef3dab7b8/contracts/1bec9281eaa84fbcac6edd6184241366?acc_token=70c750e1bef74c30b496d1d9bc8160df HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "language": "uk", 
        "title": "contract_first_document.doc", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/d8932cdabb8e4b1395ebd9320fd65868?KeyID=1db479fa&Signature=gEOPfRrgg9hJqwHuZlgh3K6mmcG44ejRg4F8o6dcjeKD4MUP2rnDVPhD97pnqvYnQURLyTk5pytkS5aq1awjAg%253D%253D", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2016-12-28T14:52:25.151056+02:00", 
        "id": "9dea4246546a486d90263ce7abb26076", 
        "dateModified": "2016-12-28T14:52:25.151081+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "language": "en", 
        "title": "contract_second_document.doc", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/a0466000c81943f0b57744dc0d7f43a1?KeyID=1db479fa&Signature=qixPFhCdePMGhbRe%252BM2ECdFltabrNW5kOMzrtY058RudsCInlIwC8U75hd2Ax0jVC%252B5VLdFQqqn7U92%252BvQWyAQ%253D%253D", 
        "format": "application/msword", 
        "title_en": "Title of Document", 
        "description_en": "Description of Document", 
        "datePublished": "2016-12-28T14:52:25.355513+02:00", 
        "documentOf": "tender", 
        "id": "93db2817cb5c4bf4b8c790583dea7f90", 
        "dateModified": "2016-12-28T14:52:25.355535+02:00"
      }
    ], 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-01-17T14:51:17.551711+02:00", 
          "endDate": "2017-01-27T14:52:30.287510+02:00"
        }, 
        "id": "70c0baf1707b42c898233ee68efdd1b3", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "contractNumber": "contract#1", 
    "period": {
      "startDate": "2016-12-28T14:52:24.894687+02:00", 
      "endDate": "2017-12-28T14:52:24.894729+02:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "valueAddedTaxIncluded": true
    }, 
    "dateSigned": "2016-12-28T14:52:24.717158+02:00", 
    "awardID": "1b3dc2749ae9466a8ba3514f6557e7ba", 
    "id": "1bec9281eaa84fbcac6edd6184241366", 
    "contractID": "UA-2016-12-28-000001-1"
  }
}

