PATCH /api/2.3/tenders/16a6ec1ed36341f3b3a6e63ef3dab7b8/contracts/1bec9281eaa84fbcac6edd6184241366/documents/93db2817cb5c4bf4b8c790583dea7f90?acc_token=70c750e1bef74c30b496d1d9bc8160df HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 106
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "title_en": "Title of Document", 
    "language": "en", 
    "description_en": "Description of Document"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "language": "en", 
    "title": "contract_second_document.doc", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/a0466000c81943f0b57744dc0d7f43a1?KeyID=1db479fa&Signature=qixPFhCdePMGhbRe%252BM2ECdFltabrNW5kOMzrtY058RudsCInlIwC8U75hd2Ax0jVC%252B5VLdFQqqn7U92%252BvQWyAQ%253D%253D", 
    "format": "application/msword", 
    "title_en": "Title of Document", 
    "description_en": "Description of Document", 
    "datePublished": "2016-12-28T14:52:25.355513+02:00", 
    "documentOf": "tender", 
    "id": "93db2817cb5c4bf4b8c790583dea7f90", 
    "dateModified": "2016-12-28T14:52:25.355535+02:00"
  }
}

