PATCH /api/2.3/tenders/b02837237aa446fc89834caae9d827c3/bids/df4b9461b03942968f1cbd7a1cc5459f?acc_token=aba85521db8d469b886d4dc492d5bc39 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 98
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "pending", 
    "lotValues": [
      {
        "relatedLot": "7e10c7d27c3f4287b7459171c1cfce1c"
      }
    ]
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "selfEligible": true, 
    "lotValues": [
      {
        "relatedLot": "7e10c7d27c3f4287b7459171c1cfce1c", 
        "date": "2016-12-28T14:51:55.588847+02:00", 
        "status": "pending"
      }
    ], 
    "selfQualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2016-12-28T14:51:55.588606+02:00", 
    "id": "df4b9461b03942968f1cbd7a1cc5459f"
  }
}

