PATCH /api/2.3/tenders/b02837237aa446fc89834caae9d827c3/qualifications/bfcafb2d098e42deb26149ec98063167?acc_token=5a587664b930494c9248c61cb14b3086 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "lotID": "7e10c7d27c3f4287b7459171c1cfce1c", 
    "eligible": true, 
    "qualified": true, 
    "bidID": "65ec0423061a4844900093b27c427b3b", 
    "date": "2016-12-28T14:51:56.607589+02:00", 
    "id": "bfcafb2d098e42deb26149ec98063167"
  }
}

