GET /api/2.3/tenders/b02837237aa446fc89834caae9d827c3 HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.tendering", 
    "tenderID": "UA-2016-12-28-000001", 
    "tenderPeriod": {
      "startDate": "2016-12-28T14:51:54.853866+02:00", 
      "endDate": "2017-01-28T14:51:17.551817+02:00"
    }, 
    "title": "Послуги шкільних їдалень", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "enquiryPeriod": {
      "startDate": "2016-12-28T14:51:54.853866+02:00", 
      "clarificationsUntil": "2017-01-23T14:51:17.551817+02:00", 
      "endDate": "2017-01-18T14:51:17.551817+02:00", 
      "invalidationDate": "2016-12-28T14:51:55.305053+02:00"
    }, 
    "complaintPeriod": {
      "startDate": "2016-12-28T14:51:54.853866+02:00", 
      "endDate": "2017-01-24T00:00:00+02:00"
    }, 
    "title_en": "Services in school canteens", 
    "value": {
      "currency": "UAH", 
      "amount": 1000.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "date": "2016-12-28T14:51:54.983004+02:00", 
    "dateModified": "2016-12-28T14:51:55.307529+02:00", 
    "procurementMethodType": "competitiveDialogueEU", 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }, 
    "items": [
      {
        "relatedLot": "7e10c7d27c3f4287b7459171c1cfce1c", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-01-17T14:51:17.551445+02:00", 
          "endDate": "2017-02-16T14:51:17.551562+02:00"
        }, 
        "id": "4f8e8d02b9b24b6db79a9d7aaf7c3291", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "relatedLot": "16a24f0e7e2941e8ae02248baa4e555d", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-01-17T14:51:17.551585+02:00", 
          "endDate": "2017-02-16T14:51:17.551597+02:00"
        }, 
        "id": "b527ecef89b0442e939d11585383440d", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "owner": "broker", 
    "next_check": "2017-01-28T14:51:17.551817+02:00", 
    "lots": [
      {
        "status": "active", 
        "description": "Опис Лот №1", 
        "title": "Лот №1", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2016-12-28T14:51:55.075450+02:00", 
        "id": "7e10c7d27c3f4287b7459171c1cfce1c"
      }, 
      {
        "status": "active", 
        "description": "Опис Лот №2", 
        "title": "Лот №2", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2016-12-28T14:51:55.162743+02:00", 
        "id": "16a24f0e7e2941e8ae02248baa4e555d"
      }
    ], 
    "id": "b02837237aa446fc89834caae9d827c3", 
    "awardCriteria": "lowestCost"
  }
}

