GET /api/2.3/tenders/c3c7a59ead604eba9eea2117d411c4a2/questions HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "description": "Просимо додати таблицю потрібної калорійності харчування", 
      "dateAnswered": "2016-12-28T14:52:37.220315+02:00", 
      "title": "Калорійність", 
      "date": "2016-12-28T14:52:37.119954+02:00", 
      "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
      "id": "4112f3ccb06c4139a410bb967b50a5b8", 
      "questionOf": "tender"
    }
  ]
}

