GET /api/2.3/tenders/c3c7a59ead604eba9eea2117d411c4a2/contracts/30a3825b12f3478b994ac0557ad45170?acc_token=4fe7b55f3f85463baee8e3606ed041e0 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "contract_document.doc", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/0a992635dc0f4b6f94fb8a4c42adcc2e?KeyID=fec4a383&Signature=RozqGgmmV4HjQ1Fgk0jL8mLHQih6aia9pD09KbkkSiq22dHdvkK4%252BzioDUKh%252BKyfNE0dy5LoiH0i9kJRTaFlBg%253D%253D", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2016-12-28T14:52:39.519717+02:00", 
        "id": "85f2975c54424643b8957ab264bb22c9", 
        "dateModified": "2016-12-28T14:52:39.519740+02:00"
      }
    ], 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-01-17T14:51:17.551789+02:00", 
          "endDate": "2017-01-27T14:52:47.433579+02:00"
        }, 
        "id": "dcb0d090155b4b46a232357587ee25b0", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "period": {
      "startDate": "2016-12-28T14:52:39.329933+02:00", 
      "endDate": "2017-12-28T14:52:39.329984+02:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "valueAddedTaxIncluded": true
    }, 
    "dateSigned": "2016-12-28T14:52:39.236458+02:00", 
    "awardID": "646478283ad1474aa357f0103a8ab492", 
    "id": "30a3825b12f3478b994ac0557ad45170", 
    "contractID": "UA-2016-12-28-000001-1"
  }
}

