GET /api/2.3/tenders/c3c7a59ead604eba9eea2117d411c4a2/documents?acc_token=4fe7b55f3f85463baee8e3606ed041e0 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "title": "Notice.pdf", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/ef03f19fdc8d46ab8a7bdd606b90de79?KeyID=fec4a383&Signature=wVn3j4Iy1Abw4BkJtCWtDaLqN5A%252B2A6S31bdJ0L%2FHn3l6psBkh6sxx2VwCpUuLC1ZXzbLuvqqW0tos0qf2lKCA%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2016-12-28T14:52:36.737149+02:00", 
      "id": "fa8751b55d694f108500a9b397d571cd", 
      "dateModified": "2016-12-28T14:52:36.737170+02:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "title": "AwardCriteria.pdf", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/b49033095a884966a864c9a4118fb74a?KeyID=fec4a383&Signature=uqc9LgW6FZRgeV5d%2FKG%2FbpbppyE3v8Ob0%252BEm1tdz4pvPphjD9R0gU40kc%2FLJimDw1ncsHSiPNhEuMwNK5lJDCQ%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2016-12-28T14:52:36.853436+02:00", 
      "id": "d347eda6cef74625b574b19fa821f681", 
      "dateModified": "2016-12-28T14:52:36.853467+02:00"
    }
  ]
}

