PUT /api/2.3/tenders/c3c7a59ead604eba9eea2117d411c4a2/cancellations/dbea5c05056a49fab4895ea300bd2dfd/documents/2403084fdc2c4c12af9d029f0084d5d1?acc_token=4fe7b55f3f85463baee8e3606ed041e0 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 187
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy57758053315$
Host: api-sandbox.openprocurement.org


Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "title": "Notice-2.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/c5558d789283401ab29acf38ea638b58?KeyID=fec4a383&Signature=8PTA0QztMv0z5RTsAjHhXGj7suqeTPD7BC783fVYik4NayUCCJxuVPqlE%252Be5xLxaS1%252BNx5PJGxDgdRj82uLJBg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-12-28T14:52:39.976966+02:00", 
    "id": "2403084fdc2c4c12af9d029f0084d5d1", 
    "dateModified": "2016-12-28T14:52:40.217449+02:00"
  }
}

