POST /api/2.3/tenders/c3c7a59ead604eba9eea2117d411c4a2/documents?acc_token=4fe7b55f3f85463baee8e3606ed041e0 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 193
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy329185900504$
Host: api-sandbox.openprocurement.org


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/c3c7a59ead604eba9eea2117d411c4a2/documents/d347eda6cef74625b574b19fa821f681
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "title": "AwardCriteria.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/b49033095a884966a864c9a4118fb74a?KeyID=fec4a383&Signature=uqc9LgW6FZRgeV5d%2FKG%2FbpbppyE3v8Ob0%252BEm1tdz4pvPphjD9R0gU40kc%2FLJimDw1ncsHSiPNhEuMwNK5lJDCQ%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-12-28T14:52:36.853436+02:00", 
    "id": "d347eda6cef74625b574b19fa821f681", 
    "dateModified": "2016-12-28T14:52:36.853467+02:00"
  }
}

