PATCH /api/2.3/tenders/e1c191962ff249a4981368400261b2de/questions/b50cf0062fd94b4da15f0d427cadcc9c?acc_token=64dd80e86ab942748b0396f3d3088a79 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 162
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\""
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "dateAnswered": "2016-12-28T14:52:12.270771+02:00", 
    "title": "Калорійність", 
    "date": "2016-12-28T14:52:12.174416+02:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "b50cf0062fd94b4da15f0d427cadcc9c", 
    "questionOf": "tender"
  }
}

