GET /api/2.3/verify?code=14360570 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "code": "14360570", 
    "name": "АКЦІОНЕРНЕ ТОВАРИСТВО КОМЕРЦІЙНИЙ БАНК \"ПРИВАТБАНК\"", 
    "url": "https://zqedr-api.nais.gov.ua/1.0/subjects/2842335", 
    "state": 1, 
    "state_text": "https://zqedr-api.nais.gov.ua/1.0/subjects/2842335", 
    "id": 2842335
  }
}


