PATCH /api/2.3/tenders/e1c191962ff249a4981368400261b2de/bids/482bfd0ae02842abb78a73a2e8f7a401?acc_token=d6a3ccb032f44759b89bb366413df1b1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 31
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "pending"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/e1c191962ff249a4981368400261b2de/bids/482bfd0ae02842abb78a73a2e8f7a401/documents/a49d4868750949beac4fd762603615b3?download=ed077a57610a4326bb68863bdd4c91f7", 
        "format": "application/pdf", 
        "isDescriptionDecision": false, 
        "documentOf": "tender", 
        "datePublished": "2016-12-28T14:52:12.951908+02:00", 
        "id": "a49d4868750949beac4fd762603615b3", 
        "dateModified": "2016-12-28T14:52:12.951930+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "title": "DescriptiveProposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/e1c191962ff249a4981368400261b2de/bids/482bfd0ae02842abb78a73a2e8f7a401/documents/d45df21c203e4f05b16798e67759817f?download=5b6d04fb5cdb4d8083e932e9fe489af0", 
        "format": "application/pdf", 
        "isDescriptionDecision": true, 
        "documentOf": "tender", 
        "datePublished": "2016-12-28T14:52:13.066185+02:00", 
        "id": "d45df21c203e4f05b16798e67759817f", 
        "dateModified": "2016-12-28T14:52:13.066206+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "format": "application/pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/e1c191962ff249a4981368400261b2de/bids/482bfd0ae02842abb78a73a2e8f7a401/documents/91545174a75c4dc9b1e9c23893eba718?download=15591677b7bd4b8480b11b06dead77cd", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_top_secrets.pdf", 
        "isDescriptionDecision": false, 
        "documentOf": "tender", 
        "datePublished": "2016-12-28T14:52:13.275845+02:00", 
        "id": "91545174a75c4dc9b1e9c23893eba718", 
        "dateModified": "2016-12-28T14:52:13.275867+02:00"
      }
    ], 
    "selfEligible": true, 
    "subcontractingDetails": "ДКП «Орфей», Україна", 
    "selfQualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2016-12-28T14:52:12.732307+02:00", 
    "id": "482bfd0ae02842abb78a73a2e8f7a401"
  }
}

