PATCH /api/2.3/tenders/930ca47e91de468a9fbcbee0614be168/complaints/3136905b85aa43d0b5ed98c0065dafef HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 32
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "accepted"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "accepted", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "language": "uk", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/1ca3935f093c41d78e43729cafa7f53e?KeyID=1644ffd8&Signature=m%252Bd%2FJmfAey2wR%2FiaQ7FyvAr4osi1jY%252BcRjRxLbNaq6VSKE%2F1cZkQqp2aCCY3omfxwcvjXGKs0Ianu%252BAYqVqoDA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-12-28T14:51:47.155692+02:00", 
        "id": "99e03b43fc71433f9033af0b8e0d076c", 
        "dateModified": "2016-12-28T14:51:47.155715+02:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "acceptance": true, 
    "dateAccepted": "2016-12-28T14:51:48.581780+02:00", 
    "dateSubmitted": "2016-12-28T14:51:47.677581+02:00", 
    "complaintID": "UA-2016-12-28-000001.1", 
    "date": "2016-12-28T14:51:48.585245+02:00", 
    "title": "Недостатньо інформації", 
    "type": "complaint", 
    "id": "3136905b85aa43d0b5ed98c0065dafef"
  }
}

