GET /api/2.3/verify?code=123 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 403 Forbidden
Content-Type: application/json; charset=UTF-8
{
  "status": "error", 
  "errors": [
    {
      "description": [
        {
          "message": "EDRPOU not found"
        }
      ], 
      "location": "body", 
      "name": "data"
    }
  ]
}


