GET /api/2.3/verify/%D0%90%D0%91%D0%92 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 403 Forbidden
Content-Type: application/json; charset=UTF-8
{
  "status": "error", 
  "errors": [
    {
      "description": [
        "`passport` parameter has wrong value."
      ], 
      "location": "body", 
      "name": "data"
    }
  ]
}


