PATCH /api/2.3/tenders/e9a9fb6c5c0f4d86b08f8492f72d88f6/cancellations/e6d7d25009bf439db7a7bd2516d80b3a/documents/96315b79e3484b0187622de4e3ba69cf?acc_token=28888537746344dca8c69e5b6c6e27ba HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 48
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "description": "Changed description"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "language": "uk", 
    "title": "Notice.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/da2ca052f5af47688dc26ff8a4ab9989?KeyID=d21c340f&Signature=KpL0WeLd%252BTTL7SyVM4X5SJMi0WauC%2FfoXtBYmJHgf%252B9EDpF9pblvJqrSG%2F%2FS3GWjZSsvP1mN%252BBEMDRLhKonIAg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-12-28T14:51:42.168463+02:00", 
    "id": "96315b79e3484b0187622de4e3ba69cf", 
    "dateModified": "2016-12-28T14:51:42.168487+02:00"
  }
}

