POST /api/2.3/tenders/e9a9fb6c5c0f4d86b08f8492f72d88f6/cancellations?acc_token=28888537746344dca8c69e5b6c6e27ba HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "reason": "cancellation reason"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/e9a9fb6c5c0f4d86b08f8492f72d88f6/cancellations/e6d7d25009bf439db7a7bd2516d80b3a
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "cancelled", 
    "date": "2016-12-28T14:51:41.995889+02:00", 
    "cancellationOf": "tender", 
    "id": "e6d7d25009bf439db7a7bd2516d80b3a"
  }
}

