PATCH /api/2.3/tenders/8f6b7301b0b34150b0eef76bb472cc3d/qualifications/8f2a52156fde445080c35ebd290ce1f0/complaints/17988aed2e994e7aa5e5153a687ecd2f?acc_token=238cf03ab3264b41b5ffa49dc6d9a607 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 145
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "resolved", 
    "tendererAction": "Умови виправлено"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "resolved", 
    "dateDecision": "2016-12-28T14:52:05.771824+02:00", 
    "tendererActionDate": "2016-12-28T14:52:06.183398+02:00", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Недостатньо інформації", 
    "id": "17988aed2e994e7aa5e5153a687ecd2f", 
    "tendererAction": "Умови виправлено", 
    "dateSubmitted": "2016-12-28T14:52:04.090629+02:00", 
    "complaintID": "UA-2016-12-28-000001.1", 
    "date": "2016-12-28T14:52:06.187859+02:00", 
    "acceptance": true, 
    "type": "complaint", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "language": "uk", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/5329edae1a5a4812b4784e0c224fb86e?KeyID=4fabf03a&Signature=77yVJqe2julT7NtIuTgMiOHabtPRmgBmTgQpY6mKt1AhPPMapc9CmeppDzB7oZqqEVILT8lMlAm1qgCEYKikBg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-12-28T14:52:03.971536+02:00", 
        "id": "531256fc27294c89b40f4eb7b739f58f", 
        "dateModified": "2016-12-28T14:52:03.971559+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "aboveThresholdReviewers", 
        "language": "uk", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/b3932c24a73345c4acbf851626dcd91f?KeyID=4fabf03a&Signature=j%2FUfpZetkllW77621LZGbB62LpnOGHkCrWHxSFONzGQiNjTc%252BRE4T9EL3mxuLc9mnc%252Bf0%2FbJcSZC8GlC6LS9Cw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-12-28T14:52:05.619216+02:00", 
        "id": "0c700603a9134102b9376daa7908e7da", 
        "dateModified": "2016-12-28T14:52:05.619243+02:00"
      }
    ], 
    "dateAccepted": "2016-12-28T14:52:05.069363+02:00"
  }
}

