PATCH /api/2.3/tenders/8f6b7301b0b34150b0eef76bb472cc3d/qualifications/8f2a52156fde445080c35ebd290ce1f0/complaints/366f58229051457aa01e51ac5f61533f?acc_token=ef211fff43df4b68b7ab5a31103418be HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 150
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "cancelled", 
    "cancellationReason": "Умови виправлено"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "cancelled", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "cancellationReason": "Умови виправлено", 
    "dateCanceled": "2016-12-28T14:52:04.815252+02:00", 
    "complaintID": "UA-2016-12-28-000001.6", 
    "date": "2016-12-28T14:52:04.819215+02:00", 
    "type": "claim", 
    "id": "366f58229051457aa01e51ac5f61533f"
  }
}

