GET /api/2.3/tenders/986d9887495b4e5297253ae7f613e820/bids?acc_token=4ff9bc371765466aa38eb1478c8559f6 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "active", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "public", 
          "language": "uk", 
          "title": "Proposal.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/ef2b87ff85804cb8bcf84c353ee49a77?KeyID=7fcfcd3f&Signature=Oc1%2FPNMw%252BV7JFtkvug36WXuLs7sjxSa0n7aU49GsTFyg8uXToXb510h4JEGDE6Y2PPptx4vnL2BAwV1B7b%2FSAg%253D%253D", 
          "format": "application/pdf", 
          "isDescriptionDecision": false, 
          "documentOf": "tender", 
          "datePublished": "2016-12-27T15:16:01.765931+02:00", 
          "id": "b29e2c5165b5484b92072a0c0bb9c519", 
          "dateModified": "2016-12-27T15:16:01.765951+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "buyerOnly", 
          "language": "uk", 
          "title": "DescriptiveProposal.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/986d9887495b4e5297253ae7f613e820/bids/91fae32d9cc24f46b2e32d99e28fa9b2/documents/1fdf6eb77b2549eb9af92f106600f3d7?download=66bde29552614783b63405a048558f54", 
          "format": "application/pdf", 
          "isDescriptionDecision": true, 
          "documentOf": "tender", 
          "datePublished": "2016-12-27T15:16:01.873981+02:00", 
          "id": "1fdf6eb77b2549eb9af92f106600f3d7", 
          "dateModified": "2016-12-27T15:16:01.874002+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "buyerOnly", 
          "language": "uk", 
          "format": "application/pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/986d9887495b4e5297253ae7f613e820/bids/91fae32d9cc24f46b2e32d99e28fa9b2/documents/8f7d5098f28a45aca2fb9f8a2efbcb13?download=3832f26555d3470bba59044570d06948", 
          "confidentialityRationale": "Only our company sells badgers with pink hair.", 
          "title": "Proposal_top_secrets.pdf", 
          "isDescriptionDecision": false, 
          "documentOf": "tender", 
          "datePublished": "2016-12-27T15:16:02.102401+02:00", 
          "id": "8f7d5098f28a45aca2fb9f8a2efbcb13", 
          "dateModified": "2016-12-27T15:16:02.102443+02:00"
        }
      ], 
      "id": "91fae32d9cc24f46b2e32d99e28fa9b2", 
      "tenderers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ]
    }, 
    {
      "status": "active", 
      "id": "e109724ac8434c768804a536cbb14137", 
      "tenderers": [
        {
          "contactPoint": {
            "email": "aagt@gmail.com", 
            "telephone": "+380 (322) 91-69-30", 
            "name": "Андрій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137226", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Книга»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 34", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ]
    }, 
    {
      "status": "unsuccessful", 
      "selfEligible": true, 
      "tenderers": [
        {
          "contactPoint": {
            "email": "fake@mail.com", 
            "telephone": "+380 (322) 12-34-56", 
            "name": "Іван Іваненко"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137227", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "«Снігур»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 35", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ], 
      "selfQualified": true, 
      "id": "a4ff0754f1af480988abbb0b87d05e59"
    }, 
    {
      "status": "active", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "public", 
          "language": "uk", 
          "title": "Proposal_part1.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/2b15d7cb8eb14424b4f3f7be0e7a7ebb?KeyID=7fcfcd3f&Signature=hpEqZW8OdoZsRxsWEUrnh35Ij9qnNvg%252BqM8YEAh63x24yWUOM2KmdtCTitkh%252BgTl8a3a5etL%252BFx5mjXTag22AA%253D%253D", 
          "format": "application/pdf", 
          "isDescriptionDecision": false, 
          "documentOf": "tender", 
          "datePublished": "2016-12-27T15:16:02.972542+02:00", 
          "id": "fffb76e17b7e4d33982a718bc5d19a98", 
          "dateModified": "2016-12-27T15:16:02.972561+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "buyerOnly", 
          "language": "uk", 
          "format": "application/pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/986d9887495b4e5297253ae7f613e820/bids/66587ea1d24d486286a61fec77249ffd/documents/78e493fdc08949949f3f9f1b0c047330?download=5f2ac7d54bfe4c66976ae48641938b0c", 
          "confidentialityRationale": "Only our company sells badgers with pink hair.", 
          "title": "Proposal_part2.pdf", 
          "isDescriptionDecision": false, 
          "documentOf": "tender", 
          "datePublished": "2016-12-27T15:16:02.972975+02:00", 
          "id": "78e493fdc08949949f3f9f1b0c047330", 
          "dateModified": "2016-12-27T15:16:02.972993+02:00"
        }
      ], 
      "id": "66587ea1d24d486286a61fec77249ffd", 
      "tenderers": [
        {
          "contactPoint": {
            "email": "fake@mail.com", 
            "telephone": "+380 (322) 12-34-56", 
            "name": "Іван Карпенко"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137228", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "«Кенгуру»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Коцюбинського, 15", 
            "region": "м. Запоріжжя", 
            "locality": "м. Запоріжя"
          }
        }
      ]
    }
  ]
}

