PATCH /api/2.3/tenders/986d9887495b4e5297253ae7f613e820?acc_token=4ff9bc371765466aa38eb1478c8559f6 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 45
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active.stage2.waiting"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.stage2.waiting", 
    "complaintPeriod": {
      "startDate": "2016-11-16T13:15:09.808003+02:00", 
      "endDate": "2016-12-13T00:00:00+02:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2016-11-16T13:15:09.808003+02:00", 
      "clarificationsUntil": "2016-12-12T13:15:09.808003+02:00", 
      "endDate": "2016-12-07T13:15:09.808003+02:00", 
      "invalidationDate": "2016-12-27T15:16:02.505920+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }, 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "00137226", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "title": "Калорійність", 
        "date": "2016-12-27T15:16:01.061831+02:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "dateAnswered": "2016-12-27T15:16:01.156671+02:00", 
        "id": "418c0208986a47a394115af57b6eedbd", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "986d9887495b4e5297253ae7f613e820", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/6444c9f9fbc94652b9c6972bfb1067a5?KeyID=7fcfcd3f&Signature=AwSXLyW6C9NRxLjCMrvvljxgwKa49gYsOYUfEKchV%252BKu1MX%2Fj7DCh49SFMTvCQtu4o5nXgKt%2FbJQw8HTNsvcCQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-12-27T15:16:00.714387+02:00", 
        "id": "e73d8261a4654d968762fcb78d954f3f", 
        "dateModified": "2016-12-27T15:16:00.714408+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "language": "uk", 
        "title": "AwardCriteria.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/e36cd1d53d374b87b4108660157c3621?KeyID=7fcfcd3f&Signature=8qhHoWn%252Bu4cFZtMA61vdWjljF%252BBpu29A%252BK9xQtv%252BqyCt379DSNDq6ftmDfcoQSIzDA0icrcBmNyu%2Fvkmh3WJBw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-12-27T15:16:00.823737+02:00", 
        "id": "3cf6848578aa436b92dc25f6ffd7bd04", 
        "dateModified": "2016-12-27T15:16:00.823758+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "language": "uk", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/0a881c6f63a3490d86b7b1c7a5b65b3b?KeyID=7fcfcd3f&Signature=Z9Rb2MSO3TpOk7EhalUe6sAxDTR7LrgQqE966Kjttr0lTz8BsHXWpORbJMlnmWXuE44ip5Bnc2cWgigbmRCoBA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-12-27T15:16:00.823737+02:00", 
        "id": "3cf6848578aa436b92dc25f6ffd7bd04", 
        "dateModified": "2016-12-27T15:16:00.945720+02:00"
      }
    ], 
    "title": "Послуги шкільних їдалень", 
    "qualificationPeriod": {
      "startDate": "2016-12-17T13:15:09.808003+02:00", 
      "endDate": "2016-12-27T13:15:09.808003+02:00"
    }, 
    "tenderID": "UA-2016-12-27-000001", 
    "dateModified": "2016-12-27T15:16:04.703802+02:00", 
    "numberOfBids": 3, 
    "tenderPeriod": {
      "startDate": "2016-11-16T13:15:09.808003+02:00", 
      "endDate": "2016-12-17T13:15:09.808003+02:00"
    }, 
    "qualifications": [
      {
        "status": "active", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "91fae32d9cc24f46b2e32d99e28fa9b2", 
        "date": "2016-12-27T15:16:03.395745+02:00", 
        "id": "87a05c99cee94413849200f662acf07c"
      }, 
      {
        "status": "active", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "e109724ac8434c768804a536cbb14137", 
        "date": "2016-12-27T15:16:03.527194+02:00", 
        "id": "282a525d4c8947348b240f10f1a96d6c"
      }, 
      {
        "status": "unsuccessful", 
        "eligible": false, 
        "qualified": false, 
        "bidID": "a4ff0754f1af480988abbb0b87d05e59", 
        "date": "2016-12-27T15:16:03.663975+02:00", 
        "id": "4a7cfca9e216433982f72ed20fb1d904"
      }, 
      {
        "status": "active", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "66587ea1d24d486286a61fec77249ffd", 
        "date": "2016-12-27T15:16:03.798237+02:00", 
        "id": "0767a282e3874f15aadec6fd964c0af3"
      }
    ], 
    "procurementMethodType": "competitiveDialogueEU", 
    "date": "2016-12-27T15:16:04.703802+02:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-01-16T15:15:09.809395+02:00", 
          "endDate": "2017-02-15T15:15:09.809429+02:00"
        }, 
        "id": "9d26726565f249a4a3be416ee3ae8229", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-01-16T15:15:09.809452+02:00", 
          "endDate": "2017-02-15T15:15:09.809464+02:00"
        }, 
        "id": "df9146204f8b4e33956fe1456a020289", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "bids": [
      {
        "status": "active", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "Proposal.pdf", 
            "url": "http://public.docs-sandbox.openprocurement.org/get/ef2b87ff85804cb8bcf84c353ee49a77?KeyID=7fcfcd3f&Signature=Oc1%2FPNMw%252BV7JFtkvug36WXuLs7sjxSa0n7aU49GsTFyg8uXToXb510h4JEGDE6Y2PPptx4vnL2BAwV1B7b%2FSAg%253D%253D", 
            "format": "application/pdf", 
            "isDescriptionDecision": false, 
            "documentOf": "tender", 
            "datePublished": "2016-12-27T15:16:01.765931+02:00", 
            "id": "b29e2c5165b5484b92072a0c0bb9c519", 
            "dateModified": "2016-12-27T15:16:01.765951+02:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "buyerOnly", 
            "language": "uk", 
            "title": "DescriptiveProposal.pdf", 
            "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/986d9887495b4e5297253ae7f613e820/bids/91fae32d9cc24f46b2e32d99e28fa9b2/documents/1fdf6eb77b2549eb9af92f106600f3d7?download=66bde29552614783b63405a048558f54", 
            "format": "application/pdf", 
            "isDescriptionDecision": true, 
            "documentOf": "tender", 
            "datePublished": "2016-12-27T15:16:01.873981+02:00", 
            "id": "1fdf6eb77b2549eb9af92f106600f3d7", 
            "dateModified": "2016-12-27T15:16:01.874002+02:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "buyerOnly", 
            "language": "uk", 
            "format": "application/pdf", 
            "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/986d9887495b4e5297253ae7f613e820/bids/91fae32d9cc24f46b2e32d99e28fa9b2/documents/8f7d5098f28a45aca2fb9f8a2efbcb13?download=3832f26555d3470bba59044570d06948", 
            "confidentialityRationale": "Only our company sells badgers with pink hair.", 
            "title": "Proposal_top_secrets.pdf", 
            "isDescriptionDecision": false, 
            "documentOf": "tender", 
            "datePublished": "2016-12-27T15:16:02.102401+02:00", 
            "id": "8f7d5098f28a45aca2fb9f8a2efbcb13", 
            "dateModified": "2016-12-27T15:16:02.102443+02:00"
          }
        ], 
        "selfEligible": true, 
        "id": "91fae32d9cc24f46b2e32d99e28fa9b2", 
        "subcontractingDetails": "ДКП «Орфей», Україна", 
        "date": "2016-12-27T15:16:01.542302+02:00", 
        "owner_token": "10cf679074c74a6cbfd53b53a3f75146", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }
        ], 
        "owner": "broker", 
        "selfQualified": true
      }, 
      {
        "status": "active", 
        "selfEligible": true, 
        "id": "e109724ac8434c768804a536cbb14137", 
        "date": "2016-12-27T15:16:02.717952+02:00", 
        "owner_token": "1afb606ebf4649c186a39a585074b398", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "aagt@gmail.com", 
              "telephone": "+380 (322) 91-69-30", 
              "name": "Андрій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Книга»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 34", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ], 
        "owner": "broker", 
        "selfQualified": true
      }, 
      {
        "status": "unsuccessful", 
        "selfEligible": true, 
        "id": "a4ff0754f1af480988abbb0b87d05e59", 
        "date": "2016-12-27T15:16:02.845247+02:00", 
        "owner_token": "b005f339cbb14085a48340fb632f4501", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "fake@mail.com", 
              "telephone": "+380 (322) 12-34-56", 
              "name": "Іван Іваненко"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137227", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "«Снігур»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 35", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ], 
        "owner": "broker", 
        "selfQualified": true
      }, 
      {
        "status": "active", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "Proposal_part1.pdf", 
            "url": "http://public.docs-sandbox.openprocurement.org/get/2b15d7cb8eb14424b4f3f7be0e7a7ebb?KeyID=7fcfcd3f&Signature=hpEqZW8OdoZsRxsWEUrnh35Ij9qnNvg%252BqM8YEAh63x24yWUOM2KmdtCTitkh%252BgTl8a3a5etL%252BFx5mjXTag22AA%253D%253D", 
            "format": "application/pdf", 
            "isDescriptionDecision": false, 
            "documentOf": "tender", 
            "datePublished": "2016-12-27T15:16:02.972542+02:00", 
            "id": "fffb76e17b7e4d33982a718bc5d19a98", 
            "dateModified": "2016-12-27T15:16:02.972561+02:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "buyerOnly", 
            "language": "uk", 
            "format": "application/pdf", 
            "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/986d9887495b4e5297253ae7f613e820/bids/66587ea1d24d486286a61fec77249ffd/documents/78e493fdc08949949f3f9f1b0c047330?download=5f2ac7d54bfe4c66976ae48641938b0c", 
            "confidentialityRationale": "Only our company sells badgers with pink hair.", 
            "title": "Proposal_part2.pdf", 
            "isDescriptionDecision": false, 
            "documentOf": "tender", 
            "datePublished": "2016-12-27T15:16:02.972975+02:00", 
            "id": "78e493fdc08949949f3f9f1b0c047330", 
            "dateModified": "2016-12-27T15:16:02.972993+02:00"
          }
        ], 
        "selfEligible": true, 
        "id": "66587ea1d24d486286a61fec77249ffd", 
        "date": "2016-12-27T15:16:02.972082+02:00", 
        "owner_token": "c6ec1306961c44db927402d2aa19e5f6", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "fake@mail.com", 
              "telephone": "+380 (322) 12-34-56", 
              "name": "Іван Карпенко"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137228", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "«Кенгуру»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Коцюбинського, 15", 
              "region": "м. Запоріжжя", 
              "locality": "м. Запоріжя"
            }
          }
        ], 
        "owner": "broker", 
        "selfQualified": true
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

