GET /api/2.3/tenders/986d9887495b4e5297253ae7f613e820?acc_token=4ff9bc371765466aa38eb1478c8559f6 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "complaintPeriod": {
      "startDate": "2016-11-16T13:15:09.808003+02:00", 
      "endDate": "2016-12-13T00:00:00+02:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2016-11-16T13:15:09.808003+02:00", 
      "clarificationsUntil": "2016-12-12T13:15:09.808003+02:00", 
      "endDate": "2016-12-07T13:15:09.808003+02:00", 
      "invalidationDate": "2016-12-27T15:16:02.505920+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }, 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "00137226", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "title": "Калорійність", 
        "date": "2016-12-27T15:16:01.061831+02:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "dateAnswered": "2016-12-27T15:16:01.156671+02:00", 
        "id": "418c0208986a47a394115af57b6eedbd", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "986d9887495b4e5297253ae7f613e820", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/6444c9f9fbc94652b9c6972bfb1067a5?KeyID=7fcfcd3f&Signature=AwSXLyW6C9NRxLjCMrvvljxgwKa49gYsOYUfEKchV%252BKu1MX%2Fj7DCh49SFMTvCQtu4o5nXgKt%2FbJQw8HTNsvcCQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-12-27T15:16:00.714387+02:00", 
        "id": "e73d8261a4654d968762fcb78d954f3f", 
        "dateModified": "2016-12-27T15:16:00.714408+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "language": "uk", 
        "title": "AwardCriteria.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/e36cd1d53d374b87b4108660157c3621?KeyID=7fcfcd3f&Signature=8qhHoWn%252Bu4cFZtMA61vdWjljF%252BBpu29A%252BK9xQtv%252BqyCt379DSNDq6ftmDfcoQSIzDA0icrcBmNyu%2Fvkmh3WJBw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-12-27T15:16:00.823737+02:00", 
        "id": "3cf6848578aa436b92dc25f6ffd7bd04", 
        "dateModified": "2016-12-27T15:16:00.823758+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "language": "uk", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/0a881c6f63a3490d86b7b1c7a5b65b3b?KeyID=7fcfcd3f&Signature=Z9Rb2MSO3TpOk7EhalUe6sAxDTR7LrgQqE966Kjttr0lTz8BsHXWpORbJMlnmWXuE44ip5Bnc2cWgigbmRCoBA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-12-27T15:16:00.823737+02:00", 
        "id": "3cf6848578aa436b92dc25f6ffd7bd04", 
        "dateModified": "2016-12-27T15:16:00.945720+02:00"
      }
    ], 
    "title": "Послуги шкільних їдалень", 
    "qualificationPeriod": {
      "startDate": "2016-12-17T13:15:09.808003+02:00", 
      "endDate": "2016-12-27T13:15:09.808003+02:00"
    }, 
    "tenderID": "UA-2016-12-27-000001", 
    "dateModified": "2016-12-27T15:16:04.437518+02:00", 
    "status": "active.stage2.pending", 
    "tenderPeriod": {
      "startDate": "2016-11-16T13:15:09.808003+02:00", 
      "endDate": "2016-12-17T13:15:09.808003+02:00"
    }, 
    "qualifications": [
      {
        "status": "active", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "91fae32d9cc24f46b2e32d99e28fa9b2", 
        "date": "2016-12-27T15:16:03.395745+02:00", 
        "id": "87a05c99cee94413849200f662acf07c"
      }, 
      {
        "status": "active", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "e109724ac8434c768804a536cbb14137", 
        "date": "2016-12-27T15:16:03.527194+02:00", 
        "id": "282a525d4c8947348b240f10f1a96d6c"
      }, 
      {
        "status": "unsuccessful", 
        "eligible": false, 
        "qualified": false, 
        "bidID": "a4ff0754f1af480988abbb0b87d05e59", 
        "date": "2016-12-27T15:16:03.663975+02:00", 
        "id": "4a7cfca9e216433982f72ed20fb1d904"
      }, 
      {
        "status": "active", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "66587ea1d24d486286a61fec77249ffd", 
        "date": "2016-12-27T15:16:03.798237+02:00", 
        "id": "0767a282e3874f15aadec6fd964c0af3"
      }
    ], 
    "procurementMethodType": "competitiveDialogueEU", 
    "date": "2016-12-27T15:16:04.437518+02:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-01-16T15:15:09.809395+02:00", 
          "endDate": "2017-02-15T15:15:09.809429+02:00"
        }, 
        "id": "9d26726565f249a4a3be416ee3ae8229", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-01-16T15:15:09.809452+02:00", 
          "endDate": "2017-02-15T15:15:09.809464+02:00"
        }, 
        "id": "df9146204f8b4e33956fe1456a020289", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

