PATCH /api/2.3/tenders/e1c191962ff249a4981368400261b2de?acc_token=64dd80e86ab942748b0396f3d3088a79 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 120
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "tenderPeriod": {
      "endDate": "2017-01-05T14:52:12.558357+02:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 501
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "complaintPeriod": {
      "startDate": "2016-11-30T14:52:12.384909+02:00", 
      "endDate": "2017-01-01T00:00:00+02:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2016-11-30T14:52:12.384909+02:00", 
      "clarificationsUntil": "2016-12-29T14:52:12.558357+02:00", 
      "endDate": "2016-12-26T14:52:12.558357+02:00", 
      "invalidationDate": "2016-12-28T14:52:12.624858+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2017-01-05T14:52:12.558357+02:00", 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }, 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "dateAnswered": "2016-12-28T14:52:12.270771+02:00", 
        "title": "Калорійність", 
        "date": "2016-12-28T14:52:12.174416+02:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "b50cf0062fd94b4da15f0d427cadcc9c", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "id": "e1c191962ff249a4981368400261b2de", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/973d2631ba6c4fcf8e8bd524db0c8a0f?KeyID=217af5e1&Signature=Dnxbk7w5wvy%2FU8OlycPhz4hNZMc0ndEKd6Q1THAMcB9zMiVqAT6NCju6xKewNx6hfQu0AWyxTKXdMnH1EbAnBw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-12-28T14:52:11.788610+02:00", 
        "id": "f8d80e79d7854b869d0e6736f148e5f1", 
        "dateModified": "2016-12-28T14:52:11.788655+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "language": "uk", 
        "title": "AwardCriteria.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/0689fcd7532c47d1bea8e79d416276aa?KeyID=217af5e1&Signature=e3c5cH5xuYGbX%2FIe1XKxiQ4JYtYQ3tDy%252BtMJNKVI%252Bxvjd21RCZYkJRFittIARZ71G4fVbV9K2%2FjoPmr%252BZdcuAQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-12-28T14:52:11.921869+02:00", 
        "id": "73152b37ccf04c51a5e25eac1b5ce57b", 
        "dateModified": "2016-12-28T14:52:11.921892+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "language": "uk", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/2b7403b75e494cfcbe901492acdb3148?KeyID=217af5e1&Signature=AIzJHPVlIXi1koJ8kKL5avMo6fc0Tf4owg8cmf7Uj41HamlyUiyZZoyVxP7iGI61qoesfobMBViCWS9CGMUEDg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-12-28T14:52:11.921869+02:00", 
        "id": "73152b37ccf04c51a5e25eac1b5ce57b", 
        "dateModified": "2016-12-28T14:52:12.058222+02:00"
      }
    ], 
    "title": "Послуги шкільних їдалень", 
    "tenderID": "UA-2016-12-28-000001", 
    "dateModified": "2016-12-28T14:52:12.626852+02:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2016-11-30T14:52:12.384909+02:00", 
      "endDate": "2017-01-05T14:52:12.558357+02:00"
    }, 
    "title_en": "Services in school canteens", 
    "procurementMethodType": "competitiveDialogueEU", 
    "date": "2016-12-28T14:52:11.342353+02:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-01-17T14:51:17.551445+02:00", 
          "endDate": "2017-02-16T14:51:17.551562+02:00"
        }, 
        "id": "fa3a670beef242709ae8495eaa1632ca", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-01-17T14:51:17.551585+02:00", 
          "endDate": "2017-02-16T14:51:17.551597+02:00"
        }, 
        "id": "f39db20e216742aba370c948a02f7f1d", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

